#!/bin/bash

#
# Runs all the performed analyses
#

# Indexes
python workspace/scala/findsong/analyses/scripts/create_indexes.py --indexsizes 10 20 50 100 200 500 1000 --inputfilesglob "media/music/**/*.mp3" --outputdirectory workspace/scala/findsong/analyses/data/indexes

# Extract clips
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/10/*.mp3" --length 10 --limitfiles 10 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/10
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/20/*.mp3" --length 10 --limitfiles 20 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/20
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/50/*.mp3" --length 10 --limitfiles 50 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/50
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/100/*.mp3" --length 10 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/100
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/200/*.mp3" --length 10 --limitfiles 200 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/200
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/500/*.mp3" --length 10 --limitfiles 500 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/500
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/1000/*.mp3" --length 10 --limitfiles 1000 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/1000

# Create clips with noise
cp workspace/scala/findsong/analyses/data/indexes/100 workspace/scala/findsong/analyses/data/indexes/noise
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/noise/*.mp3" --length 1 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/0/length/1
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/noise/*.mp3" --length 2 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/0/length/2
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/noise/*.mp3" --length 5 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/0/length/5
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/noise/*.mp3" --length 10 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/0/length/10
python workspace/scala/findsong/analyses/scripts/extract_clips.py --inputfilesglob "workspace/scala/findsong/analyses/data/indexes/noise/*.mp3" --length 20 --limitfiles 100 --offset 0 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/0/length/20
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/1/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 5 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/5/length/1
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/2/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 5 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/5/length/2
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/5/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 5 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/5/length/5
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/10/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 5 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/5/length/10
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/20/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 5 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/5/length/20
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/1/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 10 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/10/length/1
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/2/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 10 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/10/length/2
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/5/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 10 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/10/length/5
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/10/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 10 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/10/length/10
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/20/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 10 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/10/length/20
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/1/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 15 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/15/length/1
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/2/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 15 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/15/length/2
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/5/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 15 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/15/length/5
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/10/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 15 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/15/length/10
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/20/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 15 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/15/length/20
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/1/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 20 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/20/length/1
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/2/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 20 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/20/length/2
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/5/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 20 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/20/length/5
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/10/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 20 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/20/length/10
python workspace/scala/findsong/analyses/scripts/add_noise.py --inputfilesglob "workspace/scala/findsong/analyses/data/clips/noise/0/length/20/*.mp3" --noisefilepath workspace/scala/findsong/analyses/data/noise/bar.wav --noiseweight 20 --outputdirectorypath workspace/scala/findsong/analyses/data/clips/noise/20/length/20

# Metadata
python workspace/scala/findsong/analyses/scripts/extract_metadata.py --metadatakey artist --pathsfilepath workspace/scala/findsong/analyses/data/clips_noiseless/paths --outputfilepath workspace/scala/findsong/analyses/data/metadata/artists
ython workspace/scala/findsong/analyses/scripts/extract_metadata.py --metadatakey genre  --pathsfilepath workspace/scala/findsong/analyses/data/clips_noiseless/paths --outputfilepath workspace/scala/findsong/analyses/data/metadata/genres
python workspace/scala/findsong/analyses/scripts/extract_metadata.py --metadatakey TLEN  --pathsfilepath workspace/scala/findsong/analyses/data/clips_noiseless/paths --outputfilepath workspace/scala/findsong/analyses/data/metadata/tlens
